import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { reviewQueue, rescheduleAllReviews } from "@/lib/reviewQueue";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
if (typeof window === "undefined") {
  reviewQueue.resume().then(async () => {
    console.log("✅ Review queue started");
    await rescheduleAllReviews();
  });
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
